### PR TITLE
Code and content for workshop

### PR DESCRIPTION
**Pull request by bhoom10**
Hi,
This PR contains code and content for the workshop

Regards,
Bhoomika

### CODE REVIEW

**Comment by una-gal** [comment]
PR Looks good, only minor changes are required

### README.md
**Setup**
- if we do not use yml file, it is better to remove it (let's not confuse people)
- Jupyter lab or Jupyter notebooks should be added to requirements.txt or be mentioned at the Requirements
- if people will work without conda, then we need to activate venv and pip install libraries there
**Usage**
- make sure that Jupyter lab or Jupyter notebook picks up conda env or venv as an active kernel

### .gitignore
is missing

### Solutions folder
a notebook with solutions to the exercises is missing

**Comment by bhoom10** [comment]
I have removed the env.yml file and added .gitignore
Jupyter lab is already added to the requirements.txt file and also added the command for pip install using the requirements.txt file

Should I add the solutions to the exercises right now or after the workshop? I thought it would be better to add the solutions after the workshop. Additionally, instructions for activating the conda environment and ensuring that it is picked up by Jupyter have been added

**Comment by una-gal** [comment]
Thanks a lot for updates.
It is better to add solutions now, so we will have a finalized workshop.

**Comment by bhoom10** [comment]
I have now added the exercise solutions in the solutions folder

**Pull request merged**
